const mongoose = require("mongoose");
const Song = require("./models/song");
const dotenv = require("dotenv");

dotenv.config();

mongoose
  .connect(
    process.env.MONGODB_URI ||
      "mongodb+srv://melodia:AH90XFs9xABUhlIi@melodia.woowq8n.mongodb.net/"
  )
  .then(() => console.log("Connected to MongoDB for seeding"))
  .catch((err) => console.error("Connection error:", err));

const sampleSongs = [
  {
    title: "Luther",
    artist: "Kendrick Lamar & SZA",
    image:
      "https://i1.sndcdn.com/artworks-y6WaHzlvp7PbwkLT-JlZicw-t500x500.png",
    audioUrl: "https://example.com/songs/luther.mp3",
    genre: "hip-hop",
    mood: "intense",
    duration: 210,
    releaseDate: new Date("2025-06-01"),
    trendingScore: 98,
  },
  {
    title: "Die With a Smile",
    artist: "Lady Gaga & Bruno Mars",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVHYXtm6qFO-wc7bCDDKfe2I1BlLEap1y3mQ&s",
    audioUrl: "https://example.com/songs/die-with-a-smile.mp3",
    genre: "pop",
    mood: "romantic",
    duration: 195,
    releaseDate: new Date("2025-05-15"),
    trendingScore: 96,
  },
  {
    title: "Not Like Us",
    artist: "Kendrick Lamar",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKhVmdXl7HMpNew_ukSnW1J-AHuKL9ttXxCg&s",
    audioUrl: "https://example.com/songs/not-like-us.mp3",
    genre: "hip-hop",
    mood: "aggressive",
    duration: 225,
    releaseDate: new Date("2025-06-10"),
    trendingScore: 94,
  },
  {
    title: "Apt.",
    artist: "ROSÉ & Bruno Mars",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6eZuiuDjY0As3mmPTSvaJP1lcrTsqoe5XfA&s",
    audioUrl: "https://example.com/songs/apt.mp3",
    genre: "pop",
    mood: "upbeat",
    duration: 180,
    releaseDate: new Date("2025-06-05"),
    trendingScore: 92,
  },
  {
    title: "Birds Of A Feather",
    artist: "Billie Eilish",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQen_BB6_1o2HFzxDIqYkjDHkQSAgsZmW12Qw&s",
    audioUrl: "https://example.com/songs/birds-of-a-feather.mp3",
    genre: "alternative",
    mood: "emotional",
    duration: 200,
    releaseDate: new Date("2025-05-20"),
    trendingScore: 90,
  },
  {
    title: "Nokia",
    artist: "Drake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFO7SH_Xoll3n-4Mv65rd-4YsMSuQIygM84A&s",
    audioUrl: "https://example.com/songs/nokia.mp3",
    genre: "rap",
    mood: "confident",
    duration: 215,
    releaseDate: new Date("2025-06-15"),
    trendingScore: 88,
  },
  {
    title: "DTMF",
    artist: "Bad Bunny",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiqlP4JTrpKgj_AOGM9cTlyJLECrbv9OajMA&s",
    audioUrl: "https://example.com/songs/dtmf.mp3",
    genre: "reggaeton",
    mood: "festive",
    duration: 230,
    releaseDate: new Date("2025-05-25"),
    trendingScore: 91,
  },
  {
    title: "A Bar Song (Tipsy)",
    artist: "Shaboozey",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSivYgM412zi8r36MWVvCC_7gS6FG6BJAdCEQ&s",
    audioUrl: "https://example.com/songs/a-bar-song.mp3",
    genre: "country-rap",
    mood: "fun",
    duration: 185,
    releaseDate: new Date("2025-06-01"),
    trendingScore: 89,
  },
  {
    title: "Lose Control",
    artist: "Teddy Swims",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTysIhH41RDlV9LKs4jUytzvLlGHVkzwbOnng&s",
    audioUrl: "https://example.com/songs/lose-control.mp3",
    genre: "r&b",
    mood: "passionate",
    duration: 190,
    releaseDate: new Date("2025-05-10"),
    trendingScore: 87,
  },
  {
    title: "Espresso",
    artist: "Sabrina Carpenter",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPdnZ2EKT3p7TTNn7h9XEmUb-LAASbwlisZA&s",
    audioUrl: "https://example.com/songs/espresso.mp3",
    genre: "pop",
    mood: "playful",
    duration: 175,
    releaseDate: new Date("2025-04-15"),
    trendingScore: 93,
  },
  {
    title: "Beautiful Things",
    artist: "Benson Boone",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVuwjUoHY1AeJXYaS5uoQAWNDK_MwDqBtjgQ&s",
    audioUrl: "https://example.com/songs/beautiful-things.mp3",
    genre: "pop",
    mood: "heartwarming",
    duration: 200,
    releaseDate: new Date("2025-05-01"),
    trendingScore: 85,
  },
  {
    title: "Timeless",
    artist: "The Weeknd & Playboi Carti",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ16eZwCI_doWZcPb-vB0nfJ1fZli8DhoXAGg&s",
    audioUrl: "https://example.com/songs/timeless.mp3",
    genre: "r&b",
    mood: "mysterious",
    duration: 220,
    releaseDate: new Date("2025-06-20"),
    trendingScore: 83,
  },
 {
  title: "Midnight Sky",
  artist: "Miley Cyrus",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU1bGR6L06Zu802_LBIzGyld1Uj1xDpx5PNg&s",
  audioUrl: "https://example.com/songs/midnight-sky.mp3",
  genre: "pop-rock",
  mood: "empowering",
  duration: 204,
  releaseDate: new Date("2025-06-12"),
  trendingScore: 88,
},
{
    title: "Levitating",
    artist: "Dua Lipa",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUSanqMLiJmLO7U_z7KNjPjEa2KAW-RWUb6A&s",
    audioUrl: "https://example.com/songs/levitating.mp3",
    genre: "pop",
    mood: "uplifting",
    duration: 205,
    releaseDate: new Date("2025-05-05"),
    trendingScore: 87,
  },
  {
    title: "Good 4 U",
    artist: "Olivia Rodrigo",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEvQJbI8MyGBPJfqS3atn8BZ3zKPS0x9hcTQ&s",
    audioUrl: "https://example.com/songs/good-4-u.mp3",
    genre: "pop-punk",
    mood: "angry",
    duration: 180,
    releaseDate: new Date("2025-04-25"),
    trendingScore: 90,
  },
  {
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqoJqJ7aIbDQqTqHh9oncbmdVv3N06rjCRfw&s",
    audioUrl: "https://example.com/songs/stay.mp3",
    genre: "pop",
    mood: "emotional",
    duration: 190,
    releaseDate: new Date("2025-05-15"),
    trendingScore: 91,
  },
  {
    title: "Peaches",
    artist: "Justin Bieber ft. Daniel Caesar & Giveon",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzjnI3IWks3yG1aEpKRxsilLMz-rqLj9acg&s",
    audioUrl: "https://example.com/songs/peaches.mp3",
    genre: "r&b",
    mood: "smooth",
    duration: 200,
    releaseDate: new Date("2025-06-05"),
    trendingScore: 88,
  },
  {
    title: "drivers license",
    artist: "Olivia Rodrigo",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk38yy1W73AvXf0-fYLURKVP_Ojr64KSWJ9g&s",
    audioUrl: "https://example.com/songs/drivers-license.mp3",
    genre: "pop",
    mood: "heartbroken",
    duration: 245,
    releaseDate: new Date("2025-05-10"),
    trendingScore: 92,
  },
  {
    title: "Adore You",
    artist: "Harry Styles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvyIyUk0AwEhSeudAlI1lWAyzm_Xm_2CW-3A&s",
    audioUrl: "https://example.com/songs/adore-you.mp3",
    genre: "pop",
    mood: "romantic",
    duration: 200,
    releaseDate: new Date("2025-05-20"),
    trendingScore: 86,
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe6fvWOCBSMXrMTKbAIcxWvy7J8gxTlYP6Pg&s",
    audioUrl: "https://example.com/songs/shape-of-you.mp3",
    genre: "pop",
    mood: "upbeat",
    duration: 235,
    releaseDate: new Date("2025-04-10"),
    trendingScore: 88,
  },
  {
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjKsgvl6E4DyEm3mhYMmurPQohkluAHVzR3w&s",
    audioUrl: "https://example.com/songs/watermelon-sugar.mp3",
    genre: "pop",
    mood: "summery",
    duration: 180,
    releaseDate: new Date("2025-05-25"),
    trendingScore: 90,
  },

  {
    title: "Cry For Me",
    artist: "The Weeknd",
    image: "https://res.cloudinary.com/dbgueh6q5/image/upload/v1751550682/images_9_lwddol.jpg",
    audioUrl: "https://example.com/songs/cry-for-me.mp3",
    genre: "r&b",
    mood: "sad",
    duration: 210,
    releaseDate: new Date("2025-05-25"),
    trendingScore: 84,
  },
  {
    title: "Ordinary",
    artist: "Alex Warren",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIgfjhqbpva6nbL14ZY9y3y3JXJQsfXJmaiA&s",
    audioUrl: "https://example.com/songs/ordinary.mp3",
    genre: "pop",
    mood: "reflective",
    duration: 195,
    releaseDate: new Date("2025-06-15"),
    trendingScore: 82,
  },
];

async function seedDatabase() {
  try {
    await Song.deleteMany();
    await Song.insertMany(sampleSongs);
    console.log("Database seeded with sample songs");
    mongoose.connection.close();
  } catch (error) {
    console.error("Seeding error:", error);
    mongoose.connection.close();
  }
}

seedDatabase();
